### ISSUE TITLE
写得一坨屎，还好意思发出来，拉积

### ISSUE THREAD

**Issue by fnyexx** [gudqs7/uni-app-sockjs-stomp#1]
程序都跑不通，还在各大网站发布

**Comment by gudqs7** [comment]
你也遇到这个问题啊, 可惜, 我告诉了你原理, 你就是不会
伸手党伸手发现接到一坨不明物, 它习惯性的张嘴吃了进去
啊, 我的天, 刚才是什么东西!!!!!!
